spring.application.name=pokemon-service

# Enable Caffeine Cache
spring.cache.type=caffeine

# Logging
logging.level.root=INFO
logging.level.com.bolttedex=DEBUG

# PokeAPI Base URL
pokeapi.base.url=https://pokeapi.co/api/v2

scheduler.pokemon.refresh.rate=1800000
spring.lifecycle.timeout-per-shutdown-phase=30s

server.port=8080